name: Automated Tests
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [^11.0, ^12.0]	
        dependency-version: [prefer-lowest, prefer-stable]
        include:

          - laravel: ^11.0
            testbench: ^9.0
            phpunit: ^10.5

          - laravel: ^12.0
            testbench: ^10.0
            phpunit: ^11.5.3

        exclude:
            - php: 8.4
              laravel: ^11.0
              dependency-version: prefer-lowest

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - (${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@2.28.0
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: composer test